### ISSUE TITLE
Term detection fails on *BSD

### ISSUE THREAD

**Issue by bbusse** [octogo/log#3]
This is due to unix.TCGETS being undefined. This is used in 'pkg/log/output_file.go' line 87

What works is '_, err := unix.IoctlGetTermios(int(fOut.File.Fd()), unix.TIOCGETA)'

This could/should be solved at build time, probably in a similar way as here:
https://sourcegraph.com/github.com/sirupsen/logrus/-/commit/41ee4dd36547ea07a3ffc951db6c341988569d5d?visible=6

**Comment by baccenfutter** [comment]
@bbusse thanks for reporting! I am happy to see this package being adopted by other projects.

Would you mind to test above commit?
*(It's my first time working with build constraints)*

**Comment by bbusse** [comment]
Tested, works for me! Thanks for super fast reply and fix!
